### ISSUE TITLE
Difference vs std

### ISSUE THREAD

**Issue by dkrikun** [syvex/native#2]
Could you please explain what values does native adds over plain C++ std?
Also, why there is a need to typedef in types.h, i.e. what's wrong with the standard C++11 types?

**Comment by syvex** [comment]
There are a few main benefits for using native::istring over std::string:
- It's much faster. By avoiding the need to implement for std::allocator, we can just use malloc to speed up allocations on the heap.
- istring is immutable. This comes with the benefit of being completely thread safe. You can safely pass an istring to another thread or lambda without any extra heap allocations.
- istring cashes it's hash value. When doing repeated look-ups in unordered containers, there is no need to rehash the value of the string.

There is also a string_builder class now that is between %50-%200 faster. This is achieved by not having to deal with silly things like widen or locales, and using other memory optimizations.

types.h is just a convenience wrapper for the standard types so that they are in the `native` namespace. Now that I look at it again though, it's not really doing much. I went ahead and removed it.
